### ISSUE TITLE
Unable to reboot RPI image

### ISSUE THREAD

**Issue by tkundhi** [ryankurte/docker-rpi-emu#14]
I've installed docker-rbi-emu from Dockerhub onto Docker for Mac. I am execute the following command and I get the shell.

docker run -it --rm --privileged=true -v /Users/tk/projects/images:/usr/rpi/images -w /usr/rpi ryankurte/docker-rpi-emu /bin/bash -c './run.sh images/2017-11-29-raspbian-stretch-lite.img /bin/bash'

However I can't reboot. 

**Here is an example.**
root@cffdf720a6ec:/# sudo reboot
sudo: unable to resolve host cffdf720a6ec
Failed to connect to bus: No such file or directory
Failed to talk to init daemon.

**Another example**
root@cffdf720a6ec:/# shutdown -r now
Failed to connect to bus: No such file or directory
Failed to talk to init daemon.

**3rd example. This time I tried the login command instead of going straight to bash.**
docker run -it --rm --privileged=true -v /Users/tk/projects/images:/usr/rpi/images -w /usr/rpi ryankurte/docker-rpi-emu /bin/bash -c './run.sh images/2017-11-29-raspbian-stretch-lite.img login'
Attempting to mount images/2017-11-29-raspbian-stretch-lite.img to /media/rpi
Attached base loopback at: /dev/loop0
Located partitions: p1 (/boot) at 8192 and p2 (/) at 94208
Closed loopback /dev/loop0
Mounted to /media/rpi and /media/rpi/boot
Bootstrapping Qemu

**Pi is up and I login in as user pi.**
df7b99443f3f login: pi
Password: 
Last login: Wed Feb 21 20:20:00 UTC 2018 on UNKNOWN
Linux df7b99443f3f 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

**Reboot attempted**
pi@df7b99443f3f:~ $ sudo reboot
sudo: unable to resolve host df7b99443f3f
Failed to connect to bus: No such file or directory
Failed to talk to init daemon.

**Comment by ryankurte** [comment]
So this doesn't launch the whole OS (or even the init system), just the /bin/bash process in a chroot from where you can run things.
Because of that reboot doesn't really make sense. It's probably possible to launch the whole OS in qemu, but, I haven't worked out how.

**Comment by tkundhi** [comment]
@ryankurte thanks for clarifying.

**Comment by ryankurte** [comment]
No worries!
